version: 2

project_name: prismgo-lens

before:
  hooks:
    - go mod download

builds:
  - id: prismgo-lens
    main: ./cmd/prismgo-lens
    binary: prismgo-lens
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: prismgo-lens
    ids:
      - prismgo-lens
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
